version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.2-git
    steps:
      - checkout
#       - setup_remote_docker
      - run:
        name: Build
        command: |
          docker build . -t nginx-sample
